print("Hi this is a python calculator to do all ")
a= int(input("enter first number"))
b= int(input("enter second number"))
print(type(a))
print(type(b))
print(a+b, "Addition")
print(a-b, 'Subtraction')
print(a*b, "Multiplication")
print(a/b, "Division")
print(a//b, "Floor Division")
print(a%b, "Modulus(reminder)")
print(a**b, 'a to the power b')
